# Generated by Django 4.2.7 on 2026-03-14 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('result', models.CharField(max_length=32)),
                ('confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetectionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_frames', models.IntegerField(default=0)),
                ('fatigue_frames', models.IntegerField(default=0)),
                ('max_warning_level', models.CharField(default='normal', max_length=20)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='DetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ear', models.FloatField(default=0.0)),
                ('mar', models.FloatField(default=0.0)),
                ('pitch', models.FloatField(default=0.0)),
                ('fatigue_level', models.CharField(default='alert', max_length=20)),
                ('warning_level', models.CharField(default='normal', max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='detection.detectionsession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
