# Generated by Django 4.2.7 on 2026-03-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='detectionlog',
            index=models.Index(fields=['session', 'timestamp'], name='detection_d_session_243c6a_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionlog',
            index=models.Index(fields=['warning_level'], name='detection_d_warning_c96e67_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionsession',
            index=models.Index(fields=['user_id', 'start_time'], name='detection_d_user_id_e13fde_idx'),
        ),
    ]
